# config-repo/commande-service.yml
spring:
  datasource:
    url: jdbc:h2:mem:commandedb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
resilience4j:
  circuitbreaker:
    instances:
      produitCB:
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
  # ...
application:
  some-commande-property: "Hello from the Config Server - Commandes!"
