server:
  port: 8083

spring:
  datasource:
    url: jdbc:h2:mem:notificationdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092  # If using Docker or diff. IP, adapt
